version: '3'
services:
    starwarsapi:
        image: 'order-backend-api'
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
        - '4000:4000'
        environment:
        - NODE_ENV=development
        - PORT=4000
